### ISSUE TITLE
adding already added student through excel

### ISSUE THREAD

**Issue by ervinayakpatil** [pundliksarafdar/code#134]
Role : owner
Uname : Classowner3
Psswd : Passwd@123
Module : manage student
Functionality : add student through file 
issue : It don't check whether student already present or not. 
![student upload excel already added student](https://cloud.githubusercontent.com/assets/14939837/16742654/493b7ca4-47c6-11e6-85fb-8e34d09d2e8e.png)

**Comment by amit-meshram** [comment]
What if two student with same Firstname Lastname present in a class. Should we ask second student to change his/her name?

**Comment by amit-meshram** [comment]
Please also confirm if this works correctly while adding student manually. Because same code is used in both cases.
