### ISSUE TITLE
Invalid 'Start Time' and 'End time' are invalid

### ISSUE THREAD

**Issue by amit-meshram** [pundliksarafdar/code#157]
Login : classowner2
Password : Passwd@123

I have schedules dome lectures on 2016-07-01. The time which I selected for these lectures is different than what is being displayed. Please check below screen.

![image](https://cloud.githubusercontent.com/assets/7904900/16894094/f47d7d0a-4b69-11e6-949d-55c05314c0a1.png)

Its being observed that time table is not displaying the scheduled lectures for this user. It is displayed only after selecting 'choose date' datetimepicker. Need to debug this issue.

**Comment by pundliksarafdar** [comment]
default time set to IST

**Comment by amit-meshram** [comment]
Closing this issue as I found this is fixed now.
