### ISSUE TITLE
edit time table not working

### ISSUE THREAD

**Issue by ervinayakpatil** [pundliksarafdar/code#79]
name : classowner2
psswd : Passwd@123
module name : time table
role : owner

issue : not able to edit time table correctly

**Comment by ervinayakpatil** [comment]
1. its working only for month view. 
2. teacher for edit is not getting fetched

**Comment by ervinayakpatil** [comment]
delete time table not working

**Comment by pundliksarafdar** [comment]
Teacher is not fetch is duplicate of #84
